name: ludoteca
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_adaptive_scaffold: ^0.1.7+1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  uuid: ^3.0.7
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  mocktail_image_network: ^1.0.0

flutter:
  uses-material-design: true