name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Checkout flutter
        uses: subosito/flutter-action@v2

      - name: Analyze...
        run: flutter analyze
      
      - name: Tests...
        run: flutter test
      
      - name: Install and Build
        run: flutter build web --release --base-href /ludoteca/pr-preview/pr-${{ github.event.pull_request.number }}/ --web-renderer html

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/web/