name: Delete PR previews

on:
  pull_request:
    types:
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Remove preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/web/
          action: remove